name: E2E Playwright

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements_optimized.txt

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip wheel setuptools
          python -m pip install -r requirements.txt

      - name: Install Playwright Browsers
        uses: microsoft/playwright-github-action@v1

      - name: Start Streamlit app
        run: |
          nohup python -m streamlit run app.py --server.headless true --server.port 8501 > streamlit_ci.log 2>&1 &
          echo $! > app.pid

      - name: Wait for app to be ready
        shell: bash
        run: |
          for i in {1..120}; do
            if curl -fsS http://localhost:8501 >/dev/null 2>&1; then
              echo "App is up"; exit 0; fi; sleep 1; done; 
          echo "App did not start in time"; tail -n 200 streamlit_ci.log; exit 1

      - name: Run Playwright tests
        env:
          APP_URL: http://localhost:8501
        run: |
          python -m pytest -m playwright -q --maxfail=1 --disable-warnings --tracing=retain-on-failure

      - name: Print app log on failure
        if: failure()
        run: |
          echo '--- streamlit_ci.log (last 200 lines) ---'
          tail -n 200 streamlit_ci.log || true

      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: |
            test-results
            playwright-report
          if-no-files-found: ignore

      - name: Upload Streamlit log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: streamlit-log
          path: streamlit_ci.log
          if-no-files-found: ignore

