name: Integration & Slow Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # 毎日 03:00 UTC

concurrency:
  group: integration-slow-${{ github.ref }}
  cancel-in-progress: false

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements_optimized.txt

      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel setuptools
          python -m pip install -r requirements.txt

      - name: Run integration/slow tests (no Playwright)
        env:
          PYTHONDONTWRITEBYTECODE: 1
        run: |
          python -m pytest -m "(integration or slow) and not playwright" -q --maxfail=1 --disable-warnings --junitxml=test-results/junit.xml || exit 1

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-slow-junit
          path: test-results
          if-no-files-found: ignore

